[package]
name = "rs-svc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow="1.0"
signal-hook={version = "0.3", features = ["default", "extended-siginfo"]}